[RunAsInvoker]
# Format: L<NumCounter>=Description,Path To Exe File, Parameters
L0=CMD.EXE,CMD.EXE
L1=RegEdit,RegEdit.EXE
L2=MMC Console,mmc.exe
L3=Computer Manager,mmc.exe,compmgmt.msc
L4=Certificates,mmc.exe,certmgr.msc
[RunElevated]
# Format: L<NumCounter>=Description,Path To Exe File, Parameters
L0=CMD.EXE,CMD.EXE
L1=RegEdit,RegEdit.EXE
L2=MMC Console,mmc.exe
L3=Computer Manager,mmc.exe,compmgmt.msc
L4=Server Manager,ServerManager.exe
L5=Resource Manager,perfmon.exe,/res
L6=Task Manager,taskmgr.exe
[RDPConnectAsUser]
#L0=Server-TS1.Domain.Corp
[SMBConnectAsUser]
#L0=\\Server-FS1.Domain.Corp\Share
